spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banco
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lab:
            non_contextual_creation: true
