spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: user-eureka
      password: euakjdaskrejdnbfjka

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      enableSelfPreservation: false